"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
[ ](#3B4252)\
$python\
$username\
[](bg:#434C5E fg:#3B4252)\
$directory\
[](fg:#434C5E bg:#4C566A)\
$git_branch\
$git_status\
[](fg:#4C566A bg:#F76E00)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#F76E00 bg:#e83a00)\
$docker_context\
[](fg:#e83a00 bg:blue)\
$os\
[ ](blue)\
"""

right_format = """
[ ](blue)\
$time
[ ](blue)\
"""

command_timeout = 500

[username]
show_always = true
style_user = "bg:#3B4252"
style_root = "bg:#3B4252"
format = '[$user ]($style)'

[directory]
style = "bg:#434C5E"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#F76E00"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#F76E00"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#F76E00"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#4C566A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#4C566A"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#F76E00"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#F76E00"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#F76E00"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#F76E00"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#F76E00"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#F76E00"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:#F76E00"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = " "
style = "bg:#F76E00"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = 'fg:black bg:blue'
format = '[ $time ]($style)'

[os]
format = "[ $symbol ($type )]($style)"
style = 'fg:black bg:blue'
disabled = false

[os.symbols]
Arch = "󰣇"
Fedora = ""
